prefix = "miao"

[grpc]
name = "content"
listenOn = "127.0.0.1:8085"

[http]
listenOn = "127.0.0.1:8084"

[etcd]
hosts = ["127.0.0.1:2379"]
key = "content"

[mysql]
# etcd 默认mysql
key = "mysql"

# 自定义
username = ""
password = ""
address = ""
database = ""
other = ""

dsn = ""

[traefik]
provider = "etcd"